### PR TITLE
fixes richardwilkes/gcs#518

### PR DESCRIPTION
**Pull request by ImmanuelMc**
Techniques keep their relevant data differently than skills do. So I created a FormatRelativeTechniqueSkill to handle techniques.

### CODE REVIEW

**Comment by richardwilkes** [comment]
I tested issue #518 with your changes, but they didn't seem to address the problem. If this was to fix something else, could you describe the problem and list the steps you took that exhibited it so that I can take a look?

The fix for #518 was actually very simple: see commit bb584132eac495939b577eb1f183e1fd2694fd95.

**Comment by ImmanuelMc** [comment]
I am a doofus. I was looking at that issue because it seemed straight forward, but I guess forgot the original issue while I was learning how things worked and noticed a difference in how techniques and skills display relative skill level started looking at what was going on there. 

For techniques, right now the relative skill level is just given as "+1" or "-3". My change was to make it so it says "ST+1" or "Acrobatics-3" or whatever. Dunno which is the preferred behavior.

Sorry for the confusion.

**Comment by richardwilkes** [comment]
Techniques are always relative to their parent (usually a skill, but there can be non-skill techniques). Because of this, they are always displayed as just the delta (i.e. a plain +1 or -2, etc.). The canonical form used in GURPS material actually just leaves RSL blank for Techniques. You can see this in the sample character sheet for Louis d'Antares in the Basic Set (page 313 -- he only has a single technique, Feint (Force Sword), and it has no value in the Relative Level column, although it does resolve to a +2 over his normal Force Sword skill, which is what GCS shows for convenience).

**Comment by ImmanuelMc** [comment]
Gotcha. Thank you for taking the time to explain.

**Pull request closed without merging**
